import type { Metadata } from "next";
import "../globals.css";
import { TChildren } from "@/types";
import Providers from "@/components/providers";


export const metadata: Metadata = {
    title: "Nextjs Full Authentication App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: TChildren) {
    return (
        <html lang="en">
            <head>
            </head>
            <body>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
