import type { Metadata } from "next";
import "../globals.css";
import { TChildren } from "@/types";


export const metadata: Metadata = {
    title: "Nextjs Full Authentication App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: TChildren) {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    );
}
